### ISSUE TITLE
Previous years feedback not getting entered in db

### ISSUE THREAD

**Issue by vaideshshank** [SDC-USICT/OFFS3#29]
Feedbacks of current year (2018) are getting inserted fine in the database. Feedbacks of previous years' students (2017,16,etc.) are not getting inserted leading to no records. @silent-lad

**Comment by shoryajain** [comment]
Could you upload the error log/backend console output?

**Comment by vaideshshank** [comment]
Problem solved. A mysql query was not getting executed.

**Comment by vaideshshank** [comment]
app needs to be recompiled every time a new student entry is made to the database for giving feedback.
